"""Shared fixtures for PostgreSQL integration tests.

These tests run against a **real** PostgreSQL instance. The connection string
comes from ``QUERYSHIELD_TEST_DATABASE_URL``; if it is unset, every test here
*skips* (so a plain ``pytest`` run is green without a database). CI provides a
disposable ``postgres`` service container and sets that variable — the test
environment is reproducible and never depends on a developer's personal
PostgreSQL installation (Phase 2 spec, Part 3).
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator
from uuid import uuid4

import pytest
import pytest_asyncio
from pydantic import SecretStr

from queryshield.config import DatabaseConfig
from queryshield.db import PostgreSQLAdapter

TEST_DSN_ENV = "QUERYSHIELD_TEST_DATABASE_URL"


@pytest.fixture
def test_dsn() -> str:
    dsn = os.environ.get(TEST_DSN_ENV)
    if not dsn:
        pytest.skip(
            f"set {TEST_DSN_ENV} to a disposable PostgreSQL database to run "
            "the integration tests"
        )
    return dsn


@pytest.fixture
def db_config(test_dsn: str) -> DatabaseConfig:
    # Small, fast pool for tests; connect quickly so failures surface promptly.
    return DatabaseConfig(
        url=SecretStr(test_dsn),
        pool_min_size=1,
        pool_max_size=5,
        connect_timeout=5.0,
        pool_timeout=5.0,
    )


@pytest_asyncio.fixture
async def adapter(db_config: DatabaseConfig) -> AsyncIterator[PostgreSQLAdapter]:
    async with PostgreSQLAdapter(db_config) as adapter:
        yield adapter


@pytest_asyncio.fixture
async def temp_table(adapter: PostgreSQLAdapter) -> AsyncIterator[str]:
    """Create a uniquely-named regular table, drop it afterwards.

    A *regular* (not TEMP) table is used on purpose: the pool hands out different
    connections, and only a committed regular table is visible across them, which
    is exactly what the commit/rollback tests assert. The name is generated by
    the test (a uuid4 hex), never caller input.
    """
    name = f"queryshield_it_{uuid4().hex}"
    await adapter.execute(
        f'CREATE TABLE "{name}" (id integer PRIMARY KEY, label text)',
        read_only=False,
    )
    try:
        yield name
    finally:
        await adapter.execute(f'DROP TABLE IF EXISTS "{name}"', read_only=False)
